# https://taskfile.dev
# sudo snap install task --classic
# vscode: ext install paulvarache.vscode-taskfile

version: '3'

tasks:
  lint:
    desc: Lint module
    silent: false
    cmds:
      -  golangci-lint run

  watch:
    desc: Run module
    silent: false
    cmds:
      - go get github.com/githubnemo/CompileDaemon
      - CompileDaemon --build="go build -o output/module-contact ." --command=./output/module-contact

  build:
    desc: Build module
    silent: false
    cmds:
      - go build -o output/module-contact .
    sources:
      - ./**/*.go
      - go.mod
    generates:
      - output/module-contact
    method: checksum

  test:
    desc: Test module
    silent: false
    cmds:
      - go test -v ./...