name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/podkrepi-bg/go-devcontainer:v1.0.0
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        working-directory: backend/contact
        run: task lint

      - name: Build
        working-directory: backend/contact
        run: task build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/podkrepi-bg/go-devcontainer:v1.0.0
    steps:
      - name: Test
        working-directory: backend/contact
        run: task test
        
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: backend/contact
          push: false