name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/podkrepi-bg/go-devcontainer:v1.0.0
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: task lint

      - name: Build
        run: task build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/podkrepi-bg/go-devcontainer:v1.0.0
    steps:
      - uses: actions/checkout@v2
      
      - name: Test
        run: task test
        
  build-module-docker-image:
    name: Build module docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: devops-podkrepi-bg
          password: ${{ secrets.DEVOPS_PACKAGES_TOKEN }}

      - name: Get tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/podkrepi-bg/module-contact:${{ steps.vars.outputs.tag }}

  build-migrations-docker-image:
    name: Build migrations docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: devops-podkrepi-bg
          password: ${{ secrets.DEVOPS_PACKAGES_TOKEN }}

      - name: Get tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: database/migrations
          push: true
          tags: ghcr.io/podkrepi-bg/module-contact-flyway:${{ steps.vars.outputs.tag }}